/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Echarts: typeof import('./components/Echarts/src/Echarts.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    HorizontalScroll: typeof import('./components/HorizontalScroll/src/HorizontalScroll.vue')['default']
    Icon: typeof import('./components/Icon/src/Icon.vue')['default']
    Pagination: typeof import('./components/Pagination/src/Pagination.vue')['default']
    RightMenu: typeof import('./components/RightMenu/src/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwToolTip: typeof import('./components/SpyroToolTip/src/SwToolTip.vue')['default']
    Verify: typeof import('./components/Verifition/src/Verify.vue')['default']
    VerifyPoints: typeof import('./components/Verifition/src/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./components/Verifition/src/Verify/VerifySlide.vue')['default']
  }
}
